version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: frontend-dev
    ports:
      - 4200:4200
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env.docker
networks:
  blogger_default:
    external: true
